### ISSUE TITLE
The extension window doesn't show properly

### ISSUE THREAD

**Issue by victor10292** [vrtmrz/obsidian-livesync-webclip#9] opened 2023-09-08 06:10 UTC
I built the extension from source code and loaded into Chrome (116). The dialog doesn't show all the contents. It is the same even I download the extension from Chrome Extension Store.

Could you please take a look at it?
![2023-09-08_14-10](https://github.com/vrtmrz/obsidian-livesync-webclip/assets/144417859/9be07279-e637-4eaa-8c35-57d5c292aefb)

**Comment by okyq** [comment] 2023-09-30 03:10
me too

**Comment by lincomatic** [comment] 2023-10-05 20:19
me three

**Comment by vrtmrz** [comment] 2023-10-23 01:21
Sorry for missing this issue!
It has been reproduced! I will address it in a while!

**Comment by ba0f3** [comment] 2023-10-23 23:55
+1 for Vivaldi

**Comment by gerroon** [comment] 2023-12-10 02:15
I have the same issue in Brave  :( I hope some awesome dev can fix this. This extension was one of the reasons I installed Obsidian LiveSync

**Comment by vrtmrz** [comment] 2023-12-11 04:31
I am really sorry for this delayed response.
I have been a bit busy for a while, even though some bugs are on the LiveSync.

It was heartbreaking when everyone was waiting for me. However, Just now, I posted 0.6 which has fixed this issue.
This will be published after the review by Google. Please try the latest release then.

I would love to say thank you for your patience!

**Comment by gerroon** [comment] 2023-12-11 23:59
Hey thanks for the update. The window works but I cant get either submission work or sync work because I do not see the files synced to my vault. 

I do not have e2ee password set, so i do not put anything there.  I put the url to my obsidian sync serving end point.

Interesting that I see them in the coudb admin page

![image](https://github.com/vrtmrz/obsidian-livesync-webclip/assets/8519469/2cfb131a-7c4b-4410-af01-0eeed6652102)



I also see that it is not respecting to the file saving format. I donot want them under webclip, so I changed them to another folder, and the extension still seems to be saving them under "webclip" maybe that is an issue, although I added a webclip for test and they did not show up there.

**Comment by vrtmrz** [comment] 2023-12-14 09:38
Thank you for checking the latest version! 

Without E2EE encryption, the files are stored so naive. (Due to the lack of the `Path obfuscation` feature too. Therefore, the `path` and `_id` would be the same). However, I am wondering why the `/` after `webclip` has been encoded.

Could you please check the behaviour if you have changed that `Clip to` like this?
![image](https://github.com/vrtmrz/obsidian-livesync-webclip/assets/45774780/d60abbc5-b2d3-4f76-8042-52dc454181ad)

(You can ignore `Save MHTML too`, sorry for confusing capture).

**Comment by gerroon** [comment] 2023-12-14 17:01
Here are some logs, adding a custom path `DOWNLOAD/{title}_{date}.md` does not seem to work. If I use no path "Clip to" then clipping and syncing works. I believe that it probably clips with custom path but not syncing to the client. 


Maybe you have some hard coded paths?

`12/14/2023, 10:57:20 AM->entry not found: DOWNLOAD/1. NVIDIA GPU Accelerated Computing on WSL`


It would be nice if the user does not need to clip to hard coded paths or to the root fodler since everyone has thier own methods of note taking.

**Comment by gerroon** [comment] 2023-12-14 17:20
Ok little more progress. Here I made another clip with `DOWNLOAD/{title}_{date}.md` path. As you see it the plugin logs it, but it is not listed anywhere in the vault. Then where is `Shell commands documentation - Obsidian Publish_20231214_111558.md` ?

```
, 11:15:41 AM->Looking for the point last synchronized point.
12/14/2023, 11:15:41 AM->Replication completed
12/14/2023, 11:16:07 AM->OneShot Sync begin... (sync)
12/14/2023, 11:16:07 AM->Replication activated

12/14/2023, 11:16:07 AM->Applied DOWNLOAD/Output channel - Current file - Shell commands documentation - Obsidian Publish_20231214_111558.md (DOWNLOAD%2FOutput channel - Current file - Shell commands documentation - Obsidian Publish_20231214_111558.md:1-bf9e0fc60a688d69b566560e3e12be69) change...

12/14/2023, 11:16:07 AM->Replication completed
12/14/2023, 11:16:16 AM->OneShot Sync begin... (sync)
12/14/2023, 11:16:16 AM->Looking for the point last synchronized point.
12/14/2023, 11:16:16 AM->Replication activated
12/14/2023, 11:16:17 AM->Replication completed

```

**Comment by vrtmrz** [comment] 2023-12-15 07:25
Thank you for your patience! We seem to have seen some progress.

> Maybe you have some hard coded paths?

`Clip to` is a template for the path of files in the Obsidian. 
`DOWNLOAD/{title}_{date}.md` will be interpreted as `DOWNLOAD/1. NVIDIA GPU Accelerated Computing on WSL 2 — CUDA on WSL 12.3 documentation_20231215_155449.md`  
However, your data on CouchDB seems to have them with some extra encoding ( `/` to  `%2f`). Would you mind if I ask you what browser and locale you are using? (I have checked the behaviour in Edge(120) and Chrome(120), en-GB and ja-JP). 

Thank you for the log! It indicates that files are not written in the storage. Could you please enable the verbose logs? It yields some more information.
(If written, we have seen like `DB -> STORAGE (create,plain) DOWNLOAD/1. NVIDIA GPU Accelerated Computing on WSL 2 — CUDA on WSL 12.3 documentation_20231215_155449.md`).

Just in case the reminder, make sure to disable `Suspend file watching` and `Suspend database reflecting` are disabled (on the `Hatch` pane), and all target filters are empty or disabled(on the `Sync Settings` pane).

**Comment by gerroon** [comment] 2023-12-15 16:49
I use Brave, it is set to English/US. All syncing is enabled.

My Obsidian's sync fine, I doubt it is the sync itself. My feeling is that those files are living in some kind of oblivion, limbo space and not sync back to the clients, actually.


Here i captured a page from Obsidian site, this time I used "INBOX" to see if it would make a diff. It did not, it is still not showing up on the client (which this log is from).
 
(https://publish.obsidian.md/shellcommands/Output+handling/Output+channel+-+Clipboard)

![image](https://github.com/vrtmrz/obsidian-livesync-webclip/assets/8519469/a07f9a23-d4b2-4382-a4ef-55e685cbebef)


```

12/15/2023, 10:46:18 AM->Replication activated
12/15/2023, 10:46:18 AM->Applied assets/Output channel - Clipboard - Shell commands documentation - Obsidian Publish_20231215_104611/Settings-main-output-tab.20231215_104611.png (assets%2FOutput channel - Clipboard - Shell commands documentation - Obsidian Publish_20231215_104611%2FSettings-main-output-tab.20231215_104611.png:1-3f77ba13ce4efd1a8f729c8d8e1bee78) change...
12/15/2023, 10:46:19 AM->Replication completed
12/15/2023, 10:46:20 AM->OneShot Sync begin... (sync)
12/15/2023, 10:46:20 AM->Looking for the point last synchronized point.
12/15/2023, 10:46:20 AM->Replication activated
12/15/2023, 10:46:21 AM->Replication activated
12/15/2023, 10:46:21 AM->↑0 (11) ↓1 (LIVE)
12/15/2023, 10:46:21 AM->Applied INBOX/Output channel - Clipboard - Shell commands documentation - Obsidian Publish_20231215_104611.md (INBOX%2FOutput channel - Clipboard - Shell commands documentation - Obsidian Publish_20231215_104611.md:1-fe7e742a58c1c7119b8f4b018c55a665) change...
12/15/2023, 10:46:21 AM->Replication completed
12/15/2023, 10:46:43 AM->OneShot Sync begin... (sync)
12/15/2023, 10:46:43 AM->Replication activated
12/15/2023, 10:46:44 AM->Replication completed

```

Enabled verbose logging with the same settings, captured another page from that site I gave to make sure it is not the same. I do not see it in the client, but somehow it logs them in the client.


```
12/15/2023, 10:51:46 AM->Applying assets/Output channels - Shell commands documentation - Obsidian Publish_20231215_105142/Settings-main-click-output-channels-icon.20231215_105142.png (assets%2FOutput channels - Shell commands documentation - Obsidian Publish_20231215_105142%2FSettings-main-click-output-channels-icon.20231215_105142.png: 1-7e921f6da58d5b8fbcd8c73b9977b930) change...
12/15/2023, 10:51:46 AM->Applied assets/Output channels - Shell commands documentation - Obsidian Publish_20231215_105142/Settings-main-click-output-channels-icon.20231215_105142.png (assets%2FOutput channels - Shell commands documentation - Obsidian Publish_20231215_105142%2FSettings-main-click-output-channels-icon.20231215_105142.png:1-7e921f6da58d5b8fbcd8c73b9977b930) change...
12/15/2023, 10:51:46 AM->Replication paused
12/15/2023, 10:51:46 AM->Replication completed
12/15/2023, 10:51:55 AM->OneShot Sync begin... (sync)
12/15/2023, 10:51:55 AM->Looking for the point last synchronized point.
12/15/2023, 10:51:55 AM->Replication activated
12/15/2023, 10:51:56 AM->Replication paused
12/15/2023, 10:51:56 AM->Replication activated
12/15/2023, 10:51:56 AM->Applying assets/Output channels - Shell commands documentation - Obsidian Publish_20231215_105142/Settings-modal-output.20231215_105142.png (assets%2FOutput channels - Shell commands documentation - Obsidian Publish_20231215_105142%2FSettings-modal-output.20231215_105142.png: 1-67b08902c93bb5b26468bc39a7d7c78e) change...
12/15/2023, 10:51:56 AM->Applying INBOX/Output channels - Shell commands documentation - Obsidian Publish_20231215_105142.md (INBOX%2FOutput channels - Shell commands documentation - Obsidian Publish_20231215_105142.md: 1-07b79a09e0fe9519cb12c04ba71ad97c) change...
12/15/2023, 10:51:56 AM->↑0 (16) ↓2 (LIVE)
12/15/2023, 10:51:56 AM->Applied assets/Output channels - Shell commands documentation - Obsidian Publish_20231215_105142/Settings-modal-output.20231215_105142.png (assets%2FOutput channels - Shell commands documentation - Obsidian Publish_20231215_105142%2FSettings-modal-output.20231215_105142.png:1-67b08902c93bb5b26468bc39a7d7c78e) change...
12/15/2023, 10:51:56 AM->Applied INBOX/Output channels - Shell commands documentation - Obsidian Publish_20231215_105142.md (INBOX%2FOutput channels - Shell commands documentation - Obsidian Publish_20231215_105142.md:1-07b79a09e0fe9519cb12c04ba71ad97c) change...
12/15/2023, 10:51:56 AM->Replication paused
12/15/2023, 10:51:56 AM->Replication completed

```

**Comment by gerroon** [comment] 2023-12-27 22:47
So I think this has something to do with "conbvert non path obfuscated" when I ran that ooeration in the mobile, all those files clipped files showed up. Maybe they are non path?NOt sure what that means

**Comment by victor10292** [comment] 2024-09-10 08:14
I tried the latest version. The content of the page could be clipped and saved into remote database. However it fails to synchronize to my client. The part of log messages related to this failure are attached. The file seems to be skipped to save. Could you please take a look at it?

![image](https://github.com/user-attachments/assets/a77c1320-ebe2-42cd-bba7-f82a3e48efcc)

**Closed as completed** 2024-12-14 04:21 UTC
